"""empty message

Revision ID: 537410fb97b3
Revises: 36b93d81ad60
Create Date: 2015-02-25 13:10:59.856836

"""

# revision identifiers, used by Alembic.
revision = '537410fb97b3'
down_revision = '36b93d81ad60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Votjech', sa.String(), nullable=False),
    sa.Column('Hahn', sa.String(), nullable=False),
    sa.Column('Muz', sa.Boolean(name='zena'), nullable=True),
    sa.Column('datum_insertu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_loguser'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_loguser_Hahn', 'loguser', ['Hahn'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loguser_Hahn', table_name='loguser')
    op.drop_table('loguser')
    ### end Alembic commands ###
